apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-kubernetes-autoscaling
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: demo-kubernetes-autoscaling
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /go/bin/kubernetes-autoscaling --port=8080
        image: kendo5731/demo-kubernetes-autoscaling:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        name: demo-kubernetes-autoscaling
        resources:
          request:
            cpu: 100m
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.3
        command:
        - /monitor
        - --source=:http://localhost:8080
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)
        resources:
          limits:
            cpu: 100m
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: demo-kubernetes-autoscaling
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: demo-kubernetes-autoscaling
