apiVersion: v1
kind: Service
metadata:
  name: demo-kubernetes-autoscaling
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: demo-kubernetes-autoscaling
